---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  REDIS_HOST: "{{ .Release.Name }}-redis-master"