---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
      app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.port }}